case erlang:function_exported(rebar3, main, 1) of
    true -> % rebar3
        CONFIG;
    false -> % rebar 2.x or older
        %% Rebuild deps, possibly including those that have been moved to
        %% profiles
        [{deps, [
            {lager, ".*", {git, "https://github.com/basho/lager.git", {tag, "3.0.1"}}}
           ,{jsx,   ".*", {git, "https://github.com/talentdeficit/jsx.git", {tag, "v2.7.1"}}}
        ]} | [Config || {Key, _Value}=Config <- CONFIG, Key =/= deps]]
end.
